apiVersion: v1
kind: Namespace
metadata:
  name: openshift-console-user-settings
---
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: openshift-console-user-settings
  labels:
    kubernetes.io/metadata.name: openshift-console-user-settings
spec: {}
status:
  phase: Active
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: openshift-console-user-settings
  name: user-settings-kubeadmin
data: {}
